---
- name: Copy configuration file
  copy: src={{ conf_file }} dest={{ base_path }}/conf/{{ conf_file }} owner={{ username }}

- name: Run clients
  command: >
            chdir="{{ base_path }}" 
            ./bin/client 
            -c {{ base_path }}/conf/"{{ conf_file }}" 
            -l "{{ output_file }}" 
            -s "{{ seed }}"
            -b "{{ RX_bandwidth }}"
            -t "{{ time_duration }}"
  async: "{{ time_duration }}"
  poll: 1
  register: traffic_generator

- name: Parse results
  shell: python "{{ parsing_script }}" "{{ output_file }}" >> "{{ results_file }}"
  when: traffic_generator|success

- name: Copy results' file locally
  local_action: >
            command
            scp "{{ username }}"@"{{ inventory_hostname }}":"{{ results_file }}" 
            "{{ results_file_locally }}-{{ ansible_hostname }}"
  when: "{{ cp_res_locally }}"