---
- name: Check if servers are up
  command: pgrep -x server
  register: result
  ignore_errors: True

- name: Run servers
  shell: chdir="{{ base_path }}" nohup ./bin/server -p "{{ server_port }}" &
  when: result|failed